#!/usr/bin/env node

import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedPath = 'src/debug/build-id.js';

function runtimePaths(root) {
    const files = [];
    function visit(directory) {
        for (const entry of fs.readdirSync(path.join(root, directory), { withFileTypes: true })) {
            const relative = path.posix.join(directory, entry.name);
            if (entry.isSymbolicLink()) throw new Error(`Symlink in runtime source: ${relative}`);
            if (entry.isDirectory()) {
                if (relative !== 'src/typings') visit(relative);
            } else if (entry.isFile() && /\.(?:js|mjs)$/.test(entry.name) && relative !== generatedPath) {
                files.push(relative);
            }
        }
    }
    visit('src');
    files.sort();
    if (!files.includes('src/main.mjs')) throw new Error('Missing src/main.mjs');
    return files;
}

export function runtimeBuildId(root = projectRoot) {
    const hash = createHash('sha256');
    for (const relative of runtimePaths(root)) {
        hash.update(relative, 'utf8').update('\0').update(fs.readFileSync(path.join(root, relative))).update('\0');
    }
    return hash.digest('hex');
}

function moduleContent(id) {
    return `// Generated by node tools/build-id.js generate. Do not edit by hand.\nexport const buildId = '${id}';\n`;
}

export function verifyBuildId(root = projectRoot) {
    const file = path.join(root, generatedPath);
    let actual;
    try {
        if (!fs.lstatSync(file).isFile() || fs.lstatSync(file).isSymbolicLink()) {
            throw new Error('not a regular file');
        }
        actual = fs.readFileSync(file, 'utf8');
    } catch (error) {
        if (error.code === 'ENOENT') throw new Error(`Missing ${generatedPath}; run node tools/build-id.js generate`);
        throw error;
    }
    const expected = runtimeBuildId(root);
    if (actual !== moduleContent(expected)) {
        throw new Error(`Stale or modified ${generatedPath}; run node tools/build-id.js generate, then check again`);
    }
    return expected;
}

export function generateBuildId(root = projectRoot) {
    const id = runtimeBuildId(root);
    const file = path.join(root, generatedPath);
    if (fs.existsSync(file) && fs.lstatSync(file).isSymbolicLink()) throw new Error(`Unsafe ${generatedPath}`);
    const content = moduleContent(id);
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) fs.writeFileSync(file, content);
    return id;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    try {
        const command = process.argv[2];
        if (!['generate', 'check'].includes(command) || process.argv.length !== 3) {
            throw new Error('Usage: node tools/build-id.js <generate|check>');
        }
        const id = command === 'generate' ? generateBuildId() : verifyBuildId();
        console.log(`Runtime build ID: ${id}`);
    } catch (error) {
        console.error(error.message);
        process.exitCode = 1;
    }
}
