import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { selectHealingAction, selectHealingDecision } from '../../src/tactics/healing.js';
import { moveCreeps, executeTactics } from '../../src/arena/execute.js';

const fixture = JSON.parse(fs.readFileSync(new URL('../fixtures/healing-window36-45.json', import.meta.url)));
const baseline = JSON.parse(fs.readFileSync(new URL('../fixtures/healing-window36-45-baseline.json', import.meta.url)));
const original = baseline.entries.map(wrapper => JSON.parse(wrapper.raw));
const ownId = name => `pg_player1_${name}`;
const short = id => id.replace('pg_player1_', '');

function freeze(value) {
    if (value && typeof value === 'object') {
        Object.values(value).forEach(freeze);
        Object.freeze(value);
    }
    return value;
}
freeze(fixture);
freeze(baseline);

function recordedCreep(record, calls = []) {
    const creep = {
        ...record,
        // Presence-only adapter: 1 is an eligibility sentinel, NOT observed
        // per-part HP. Preserve every recorded functioning count exactly.
        body: Object.entries(record.activeBodyParts).flatMap(([type, count]) =>
            Array.from({ length: count }, () => ({ type, hits: 1 }))),
        getRangeTo(target) { return Math.max(Math.abs(this.x - target.x), Math.abs(this.y - target.y)); },
    };
    for (const method of ['moveTo', 'heal', 'rangedHeal', 'attack', 'rangedAttack']) {
        creep[method] = target => {
            calls.push({ actorId: creep.id, method, target: { id: target.id, x: target.x, y: target.y } });
            return 0; // Mock scheduling only; never alter HP, parts or positions.
        };
    }
    return freeze(creep);
}

function unit(id, x = 0, y = 0, options = {}, calls = []) {
    return recordedCreep({ id, x, y, my: true, hits: 100, hitsMax: 100, fatigue: 0,
        activeBodyParts: { heal: 1 }, ...options }, calls);
}
const actionKey = action => action ? [short(action.target.id), action.method] : null;

// Hand-specified from the policy evaluation, not generated by the selector.
// Each row is healer_1, healer_2, healer_3, including all nine no-actions.
const expected = [
    [null, null, null],
    [null, null, null],
    [null, null, ['ranged_3', 'rangedHeal']],
    [['healer_3', 'heal'], null, ['healer_3', 'heal']],
    [['healer_3', 'rangedHeal'], ['melee_1', 'rangedHeal'], ['ranged_4', 'heal']],
    [['healer_1', 'heal'], ['healer_1', 'rangedHeal'], ['ranged_4', 'heal']],
    [['melee_1', 'rangedHeal'], ['melee_1', 'rangedHeal'], ['ranged_4', 'heal']],
    [['melee_3', 'rangedHeal'], ['melee_1', 'rangedHeal'], ['ranged_4', 'heal']],
    [['ranged_4', 'rangedHeal'], ['ranged_4', 'rangedHeal'], ['ranged_4', 'heal']],
    [['ranged_4', 'rangedHeal'], ['ranged_4', 'rangedHeal'], ['ranged_4', 'heal']],
];

function capacityTotals(actions, byId) {
    const targets = new Map();
    for (const { actorId, method, target } of actions) {
        const actor = byId.get(actorId);
        const capacity = actor.activeBodyParts.heal * (method === 'heal' ? 12 : 4);
        targets.set(target.id, (targets.get(target.id) ?? 0) + capacity);
    }
    let nominal = 0, useful = 0;
    for (const [id, capacity] of targets) {
        const target = byId.get(id);
        nominal += capacity;
        useful += Math.min(capacity, target.hitsMax - target.hits);
    }
    return [nominal, useful, nominal - useful];
}

for (const snapshot of fixture.snapshots) {
    test(`recorded tick ${snapshot.tick}: all three capacity-aware healing decisions`, () => {
        const creeps = snapshot.creeps.map(record => recordedCreep(record));
        const friends = freeze(creeps.filter(creep => creep.my && creep.hits > 0 && creep.hits < creep.hitsMax));
        const healers = [1, 2, 3].map(i => creeps.find(creep => creep.id === ownId(`healer_${i}`)));
        const actual = healers.map(healer => actionKey(selectHealingAction(healer, friends)));
        assert.deepEqual(actual, expected[snapshot.tick - 36]);
        // Input order, actor evaluation order and repeated calls cannot reserve healing.
        assert.deepEqual([...healers].reverse().map(healer =>
            actionKey(selectHealingAction(healer, freeze([...friends].reverse())))).reverse(), actual);
        for (const creep of creeps) {
            const counts = {};
            for (const part of creep.body) counts[part.type] = (counts[part.type] ?? 0) + 1;
            assert.deepEqual(counts, creep.activeBodyParts);
        }
    });
}

test('recorded full rosters preserve 128 movement decisions, 83 moves and 38 attack calls', () => {
    const normalizeAction = a => ({ method: a.method, target: { id: a.target.id, x: a.target.x, y: a.target.y },
        targetKind: a.targetKind ?? a.target.kind });
    const normalizeDecision = d => ({ phase: d.phase, channel: d.channel, actorId: d.actorId,
        outcome: d.outcome, reason: d.reason, actions: d.actions.map(normalizeAction) });
    const normalizeAttempt = a => ({ actorId: a.actorId, method: a.method,
        target: { id: a.target.id, x: a.target.x, y: a.target.y } });
    const engagements = new Map();
    let movements = 0, moves = 0, attacks = 0;
    const historicalTotals = [], candidateTotals = [];
    for (const snapshot of fixture.snapshots) {
        const calls = [], decisions = [], attempts = [], events = [];
        const creeps = snapshot.creeps.map(record => recordedCreep(record, calls));
        const byId = new Map(creeps.map(creep => [creep.id, creep]));
        const own = freeze(creeps.filter(creep => creep.my));
        const enemies = freeze(creeps.filter(creep => !creep.my && creep.hits > 0));
        const injured = freeze(own.filter(creep => creep.hits > 0 && creep.hits < creep.hitsMax));
        const flagRecord = snapshot.flags.find(flag => flag.id === snapshot.selectedFlagId);
        const flag = freeze({ ...flagRecord, my: flagRecord.owner === 'me' });
        const reporter = {
            decision(d) { decisions.push(normalizeDecision(d)); events.push(['decision', d.actorId, d.channel]); return d; },
            attempt(d, index, a, returnCode) {
                assert.equal(returnCode, 0);
                assert.deepEqual(normalizeAction(a), normalizeAction(d.actions[index]));
                attempts.push(normalizeAttempt({ ...a, actorId: d.actorId }));
                events.push(['attempt', d.actorId, d.channel]);
            },
        };
        // First engagement is tick 36. No escort movement appears in this trace;
        // allocation, holding and pairing were disabled. No engine state is advanced.
        moveCreeps(own, enemies, flag, engagements, new Map(), null, null, reporter);
        executeTactics(own, enemies, injured, reporter);
        const historical = original.filter(d => d.tick === snapshot.tick);
        for (const channel of ['movement', 'combat']) {
            assert.deepEqual(decisions.filter(d => d.channel === channel), historical
                .filter(d => d.type === 'action-decision' && d.channel === channel).map(normalizeDecision));
        }
        assert.deepEqual(calls.filter(a => !['heal', 'rangedHeal'].includes(a.method)), historical
            .filter(d => d.type === 'action-attempt' && d.channel !== 'healing').map(normalizeAttempt));
        assert.deepEqual(attempts, calls);
        for (const actor of own) {
            const eventsForActor = events.filter(e => e[1] === actor.id);
            const healDecision = eventsForActor.findIndex(e => e[0] === 'decision' && e[2] === 'healing');
            const combatDecision = eventsForActor.findIndex(e => e[0] === 'decision' && e[2] === 'combat');
            assert.ok(healDecision >= 0 && combatDecision > healDecision);
            const healAttempt = eventsForActor.findIndex(e => e[0] === 'attempt' && e[2] === 'healing');
            if (healAttempt >= 0) assert.ok(healAttempt > healDecision && healAttempt < combatDecision);
        }
        movements += decisions.filter(d => d.channel === 'movement').length;
        moves += calls.filter(a => a.method === 'moveTo').length;
        attacks += calls.filter(a => ['attack', 'rangedAttack'].includes(a.method)).length;
        historicalTotals.push(capacityTotals(historical.filter(d => d.type === 'action-attempt' && d.channel === 'healing'), byId));
        candidateTotals.push(capacityTotals(calls.filter(a => ['heal', 'rangedHeal'].includes(a.method)), byId));
    }
    assert.deepEqual([movements, moves, attacks], [128, 83, 38]);
    assert.deepEqual(historicalTotals.map(t => t[1]), [0, 0, 24, 78, 66, 54, 82, 4, 120, 120]);
    assert.deepEqual(candidateTotals.map(t => t[1]), [0, 0, 24, 84, 102, 102, 120, 120, 120, 120]);
    const sum = rows => [0, 1, 2].map(i => rows.reduce((total, row) => total + row[i], 0));
    assert.deepEqual(sum(historicalTotals), [1176, 548, 628]);
    assert.deepEqual(sum(candidateTotals), [936, 792, 144]);
});

test('historical baseline identity and tick-43 attempts remain separate from candidate expectations', () => {
    assert.deepEqual(fixture.snapshots.map(s => s.tick), [36, 37, 38, 39, 40, 41, 42, 43, 44, 45]);
    assert.equal(fixture.provenance.outputFingerprint, '1445f2969c0ffda35cf5e872d37de6aa3444ef05c981f6068c86c6853c08b3f2');
    assert.equal(fixture.provenance.buildId, 'fced5aed1e43b9c264cf3fbb7f437dfd4cf28d9175d4a6cd69b468ce57187933');
    assert.ok(fixture.snapshots.every(s => s.buildId === fixture.provenance.buildId));
    assert.ok(original.every(d => d.buildId === fixture.provenance.buildId));
    assert.equal(original.filter(d => d.type === 'action-decision' && d.channel === 'healing').length, 128);
    assert.equal(original.filter(d => d.type === 'action-attempt' && d.channel === 'healing').length, 21);
    assert.deepEqual(original.filter(d => ['43:44', '43:47', '43:50'].includes(d.recordId))
        .map(d => [short(d.actorId), short(d.target.id), d.method, d.returnCode]), [
        ['healer_1', 'healer_3', 'heal', 0], ['healer_2', 'healer_2', 'heal', 0],
        ['healer_3', 'healer_3', 'heal', 0],
    ]);
});

test('self is considered exactly once and candidate input arrays are not mutated', () => {
    const ranges = [];
    const actor = { ...unit('actor', 0, 0, { hits: 96 }),
        getRangeTo(target) { ranges.push(target.id); return Math.max(Math.abs(target.x), Math.abs(target.y)); } };
    const ally = unit('ally', 2, 0, { hits: 1 });
    const input = freeze([actor, ally, actor, ally]);
    assert.equal(selectHealingAction(actor, input).target, actor); // 4 versus 4: self wins range tie.
    assert.deepEqual(ranges, ['actor', 'ally']);
    assert.deepEqual(input, [actor, ally, actor, ally]);
});

test('living owned actors need functioning HEAL; targets must be living, owned and injured', () => {
    const ally = unit('ally', 1, 0, { hits: 50 });
    for (const options of [{ my: false }, { hits: 0 }, { activeBodyParts: {} }]) {
        assert.equal(selectHealingAction(unit('actor', 0, 0, options), [ally]), null);
    }
    const broken = { ...unit('actor'), body: [{ type: 'heal', hits: 0 }] };
    assert.equal(selectHealingDecision(broken, [ally]).reason, 'no-functioning-heal');
    const actor = unit('actor');
    assert.equal(selectHealingAction(actor, [unit('enemy', 1, 0, { my: false, hits: 1 }),
        unit('dead', 1, 0, { hits: 0 }), unit('healthy', 1, 0), unit('far', 4, 0, { hits: 1 })]), null);
});

test('self competes by capped capacity; functioning-part count changes the choice', () => {
    const ally = unit('ally', 2, 0, { hits: 20 });
    const onePart = unit('actor', 0, 0, { hits: 94 });
    const twoParts = unit('actor', 0, 0, { hits: 94, activeBodyParts: { heal: 2 } });
    assert.equal(selectHealingAction(onePart, [ally]).target, onePart); // 6 versus 4
    assert.equal(selectHealingAction(twoParts, [ally]).target, ally); // 6 versus 8
    const partlyBroken = { ...onePart, body: [{ type: 'heal', hits: 1 }, { type: 'heal', hits: 0 }] };
    assert.equal(selectHealingAction(partlyBroken, [ally]).target, partlyBroken);
    const tinySelf = unit('actor', 0, 0, { hits: 98 });
    assert.equal(selectHealingAction(tinySelf, [tinySelf, ally, tinySelf]).target, ally);
    assert.equal(selectHealingAction(onePart, []).target, onePart);
});

test('range boundaries and direct capacity take precedence over a larger distant deficit', () => {
    const actor = unit('actor');
    for (const [x, method] of [[1, 'heal'], [2, 'rangedHeal'], [3, 'rangedHeal']]) {
        assert.equal(selectHealingAction(actor, [unit('ally', x, x, { hits: 1 })]).method, method);
    }
    assert.equal(selectHealingAction(actor, [unit('far', 4, 0, { hits: 1 })]), null);
    const near = unit('z', 1, 1, { hits: 89 }), far = unit('a', 2, 0, { hits: 1 });
    assert.equal(selectHealingAction(actor, [far, near]).target, near); // 11 versus 4
});

test('ties use range then ID, not uncapped deficit, input order or role', () => {
    const actor = unit('actor');
    const near = unit('z', 2, 0, { hits: 90 }), far = unit('a', 3, 0, { hits: 1 });
    assert.equal(selectHealingAction(actor, [far, near]).target, near);
    const smallerId = unit('a', 2, 0, { hits: 90 }), largerId = unit('z', 0, 2, { hits: 1 });
    for (const candidates of [[largerId, smallerId], [smallerId, largerId]]) {
        assert.equal(selectHealingAction(actor, freeze(candidates)).target, smallerId);
    }
    const self = unit('actor', 0, 0, { hits: 88 });
    assert.equal(selectHealingAction(self, [unit('a', 1, 0, { hits: 1 }), self, self]).target, self);
});

test('mixed-body executor still preserves compatible attacks and healing-before-combat order', () => {
    const enemy = unit('enemy', 1, 0, { my: false });
    const nearby = unit('near', 1, 1, { hits: 1 });
    const distant = unit('far', 2, 0, { hits: 1 });
    for (const [friends, wanted] of [
        [[nearby], ['heal', 'rangedAttack']], [[distant], ['rangedHeal']],
        [[], ['rangedAttack', 'attack']],
    ]) {
        const calls = [];
        const actor = unit('actor', 0, 0, { activeBodyParts: { heal: 1, attack: 1, ranged_attack: 1 } }, calls);
        executeTactics([actor], [enemy], friends);
        assert.deepEqual(calls.map(c => c.method), wanted);
    }
});
